
# Generated by Django 5.1.5 on 2025-02-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eema', '0002_alter_blogpost_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('در حال بررسی', 'Waiting'), ('منتشر شده', 'Approved'), ('تایید نشده', 'Not Approved')], default='در حال بررسی', max_length=13),
        ),
    ]
