# Generated by Django 5.1.4 on 2025-01-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eema', '0002_alter_blogpost_datetime_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='blog/blogpost_cover'),
        ),
    ]
