# Generated by Django 5.1.5 on 2025-03-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eema', '0006_slide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام دوره')),
                ('description', models.TextField(verbose_name='توضیحات دوره')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
        ),
    ]
