# Generated by Django 5.1.5 on 2025-03-02 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eema', '0007_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام کامل')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت نام')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eema.course', verbose_name='دوره')),
            ],
        ),
    ]
