# Generated by Django 5.1.5 on 2025-01-18 13:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eema', '0014_alter_comment_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='short_body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
