# Generated by Django 5.1.5 on 2025-01-21 11:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eema', '0015_blogpost_short_body_alter_blogpost_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='media/blog/blogpost_cover'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='short_body',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
