# Generated by Django 5.1.5 on 2025-01-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eema', '0016_alter_blogpost_image_alter_blogpost_short_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='blog/blogpost_cover'),
        ),
    ]
