# Generated by Django 5.1.5 on 2025-02-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eema', '0027_alter_blogpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
