# Generated by Django 5.1.5 on 2025-03-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='slides/', verbose_name='تصویر')),
                ('link', models.URLField(blank=True, verbose_name='لینک')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'اسلاید',
                'verbose_name_plural': 'اسلایدها',
            },
        ),
    ]
