# Generated by Django 5.1.5 on 2025-03-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0002_slide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال'),
        ),
    ]
