# Generated by Django 5.1.5 on 2025-03-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0003_alter_slide_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
    ]
