# Generated by Django 5.1.5 on 2025-03-01 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0004_alter_slide_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slide',
        ),
    ]
